### ISSUE TITLE
Not working in singleplayer World

### ISSUE THREAD

**Issue by Fricardo17** [napalm00/unpatch-zero-tick-farms#1]
Hey, I saw you said it did not need to be installed client-side only on the server, does it still work in singleplayer worlds, because it did not for me. I have fabric installed for the correct snapshot and have the api. I also have 3 other mods installed, mini hud, REI (Roughly Enough Items), and malilib Fabric all mods are working besides unpatch-zero-tick-farms.

**Comment by napalm00** [comment]
I've just updated the mod for Minecraft 1.16.3 and tested it on singleplayer, give it another try if you can!
