### ISSUE TITLE
1.16.2/1.16.3 update?

### ISSUE THREAD

**Issue by ghost** [napalm00/unpatch-zero-tick-farms#2]
Do you have any plans for updating this mod? Thank you.

**Comment by napalm00** [comment]
Hey, I know a lot of people are looking forward to an update for this mod.
I've been sort of successful in updating it, however it crashes with a StackoverflowError for Kelp/Weeping vines and stuff that generally isn't Bamboo/Cactus/Sugarcane/Chorus fruit.
I'm pretty new to how Fabric works so it's possible I'm doing something wrong, I'll take a look at it again this weekend.

**Comment by napalm00** [comment]
Just updated for Minecraft 1.16.3.

Closed by b97e9bb
