### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by PseudoDistant** [napalm00/unpatch-zero-tick-farms#4]
Do you have any plans to continue development of this unpatch?

I have noticed that it's been a while since there's been any activity from you on GitHub.

**Comment by napalm00** [comment]
Hey, I've just updated it to Minecraft 1.16.5 (and merged the Cactus patch #3)
I try to keep this maintained whenever I can, mostly it's just re-building it for the latest version of Minecraft.
If there are any new crops that can be farmed with the 0-tick setup, let me know!

**Comment by PseudoDistant** [comment]
Alright, thank you for responding ^^ .

(For some reason I didn't get a notification...)

I'm actually making my own bug unpatcher as well, though I don't have a focus on Redstone stuff right now.
Mostly things like striders floating and stuff like that. :)
