### ISSUE TITLE
[Request] Per-block config

### ISSUE THREAD

**Issue by supersaiyansubtlety** [napalm00/unpatch-zero-tick-farms#5]
It would be great to have conifgs to individually enable/disable 0-ticking for each kind of block that can be 0-ticked. 

Personally I'd like to restore 0-ticking just for chorus flowers.

**Comment by napalm00** [comment]
Added in [v1.0.9-1.16.5](https://github.com/napalm00/unpatch-zero-tick-farms/releases/tag/v1.0.9-1.16.5) (3d925aa)

In your case the configuration would be:
```json
{
  "isZeroTickUnpatchEnabled": true,
  "isBambooZeroTickEnabled": false,
  "isCactusZeroTickEnabled": false,
  "isChorusFlowerZeroTickEnabled": true,
  "isSugarCaneZeroTickEnabled": false,
  "isVinesZeroTickEnabled": false
}
```

**Comment by supersaiyansubtlety** [comment]
Thanks!
